apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment

spec:
  replicas: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
      containers:
        - name: flask
          image: tanmaigawas/my-repo:v1.1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          env:
            - name: FLASK_ENV
              value: "production"

            - name: SECRET_KEY
              value: "dev-secret-key"

            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DB_URL

            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DB_URL

            - name: DEV_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DB_URL