sonar.projectKey=flask-mysql-docker-project2
sonar.projectName=flask-mysql-docker-project2

sonar.sources=.

sonar.python.version=3.14

sonar.exclusions=\
**/myvenv/**,\
**/.venv/**,\
**/venv/**,\
**/__pycache__/**,\
**/.pytest_cache/**,\
**/*.pyc,\
**/*.db,\
**/*.sqlite,\
**/*.sqlite3,\
**/instance/**,\
**/logs/**,\
**/migrations/**